import { TokenType } from './token.ts';

export const KEYWORDS: Record<string, TokenType> = {
  dim: TokenType.Dim,
  redim: TokenType.ReDim,
  preserve: TokenType.Preserve,
  public: TokenType.Public,
  private: TokenType.Private,
  sub: TokenType.Sub,
  function: TokenType.Function,
  end: TokenType.End,
  exit: TokenType.Exit,
  call: TokenType.Call,
  set: TokenType.Set,
  let: TokenType.Let,
  get: TokenType.Get,
  if: TokenType.If,
  then: TokenType.Then,
  else: TokenType.Else,
  elseif: TokenType.ElseIf,
  for: TokenType.For,
  to: TokenType.To,
  step: TokenType.Step,
  next: TokenType.Next,
  each: TokenType.Each,
  in: TokenType.In,
  do: TokenType.Do,
  loop: TokenType.Loop,
  while: TokenType.While,
  wend: TokenType.Wend,
  until: TokenType.Until,
  select: TokenType.Select,
  case: TokenType.Case,
  on: TokenType.On,
  error: TokenType.Error,
  resume: TokenType.Resume,
  goto: TokenType.Goto,
  with: TokenType.With,
  class: TokenType.Class,
  property: TokenType.Property,
  new: TokenType.New,
  const: TokenType.Const,
  option: TokenType.Option,
  explicit: TokenType.Explicit,
  byref: TokenType.ByRef,
  byval: TokenType.ByVal,
  optional: TokenType.Optional,
  paramarray: TokenType.ParamArray,
  rem: TokenType.Rem,
  erase: TokenType.Erase,
  as: TokenType.As,
  and: TokenType.And,
  or: TokenType.Or,
  not: TokenType.Not,
  xor: TokenType.Xor,
  eqv: TokenType.Eqv,
  imp: TokenType.Imp,
  is: TokenType.Is,
  mod: TokenType.Mod,
  integer: TokenType.Integer,
  long: TokenType.Long,
  longlong: TokenType.LongLong,
  single: TokenType.Single,
  double: TokenType.Double,
  currency: TokenType.Currency,
  string: TokenType.String,
  boolean: TokenType.Boolean,
  date: TokenType.Date,
  object: TokenType.Object,
  variant: TokenType.Variant,
  byte: TokenType.Byte,
  true: TokenType.BooleanLiteral,
  false: TokenType.BooleanLiteral,
  nothing: TokenType.NothingLiteral,
  me: TokenType.Me,
  stop: TokenType.Stop,
  null: TokenType.NullLiteral,
  empty: TokenType.EmptyLiteral,
  enum: TokenType.Enum,
  type: TokenType.Type,
};

/**
 * The keywords that real VBScript nevertheless accepts as ordinary names.
 *
 * `Dim Property` compiles and `Dim Class` does not, so neither test is right on its own:
 * parseIdentifier() refuses all of them, and parsePropertyName() (reached through
 * parseFlexibleIdentifier()) accepts every token, including the ones the language genuinely
 * reserves.
 *
 * Established by running `Dim <word>` for each of the keywords above through the real engine -
 * `cscript //E:vbscript` on Windows: these nine compile, the other 68 fail with
 * "Expected identifier".
 */
export const NAMEABLE_KEYWORDS: ReadonlySet<TokenType> = new Set([
  TokenType.Date,
  TokenType.Erase,
  TokenType.Error,
  TokenType.Explicit,
  TokenType.LongLong,
  TokenType.Object,
  TokenType.Property,
  TokenType.Step,
  TokenType.String,
]);
